# Site
name: 'realnazigif'
description: 'Welcome to my website, where you will find a collection of stunning animated GIFs of beautiful women. All of the GIFs on this site are created by me, and are designed to delight and entertain. Browse through my collection and enjoy the show!'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
avatar: 'assets/images/sal.png'

include: [ "_pages" ]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page


# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [ README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules ]